openapi: 3.0.0
info:
  title: detectSentiment
  version: '1.0'
  contact:
    name: Leor Brenman
    email: lbrenman99@hotmail.com
  description: 'Detect sentiment  '
servers:
  - url: 'http://localhost:3000'
    description: Leor Brenman
paths:
  /detectSentiment:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/sentiment.yaml
              examples:
                example-1:
                  value:
                    SentimentScore:
                      Mixed: 0.0033542951568961143
                      Positive: 0.9869875907897949
                      Neutral: 0.008563132025301456
                      Negative: 0.0010949420975521207
                    Sentiment: POSITIVE
      operationId: get-detectSentiment
      description: 'Detect sentiment of provided text. Supported languages: English, Spanish, French, German, Italian, Portugese, Arabic, Hindi, Japanese, Korean, Chinese, Chinese (Taiwanese)'
      parameters:
        - schema:
            type: string
          in: query
          name: text
          description: Text to detect sentiment of
          required: true
      tags:
        - detectSentiment
components:
  schemas: {}
tags:
  - name: detectSentiment
